## Milena Macedo



#*numpy*

Fonte:

1. [Tutorial numpy](http://cs231n.github.io/python-numpy-tutorial/)
1. [Outro Tutorial numpy](https://cadernodelaboratorio.com.br/2017/03/10/primeiras-nocoes-do-numpy-um-tutorial/)


O que é o NumPy?
----------------

O NumPy é um pacote de processamento de matriz de uso geral. Ele fornece um objeto de matriz multidimensional de alto desempenho e ferramentas para trabalhar com essas matrizes.

É o pacote fundamental para a computação científica com Python. Ele contém vários recursos, incluindo os importantes:

Um poderoso objeto de matriz N-dimensional

* Funções sofisticadas de broadcasting (transmissão)
* Ferramentas para integrar código C / C ++ e Fortran
* Recursos úteis de álgebra linear, transformação de Fourier e números aleatórios

Numpy é a biblioteca principal de computação científica em Python. Ele fornece um objeto de matriz multidimensional de alto desempenho e ferramentas para trabalhar com essas matrizes. 

Matrizes
--------

Uma matriz numpy é uma grade de valores, todos do mesmo tipo, e é indexada por uma tupla de números inteiros não negativos. O número de dimensões é a classificação da matriz; a forma de uma matriz é uma tupla de números inteiros, fornecendo o tamanho da matriz ao longo de cada dimensão.

Podemos inicializar matrizes numpy a partir de listas Python aninhadas e acessar elementos usando colchetes:


In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Cria uma matriz (array) de posto 1
print(type(a))            # Imprime "<class 'numpy.ndarray'>"
print(a.shape)            # Imprime "(3,)"
print(a[0], a[1], a[2])   # Imprime "1 2 3"
a[0] = 5                  # Modifica um elemento da matriz (array)
print(a)                  # Imprime "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Cria uma matriz de posto 2
print(b.shape)                     # Imprime "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Imprime "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy também fornece muitas funções para criar matrizes (arrays):

* **ones**: Matriz formada apenas de 1.

* **zeros**: Matriz nula em que todos os elementos são nulos, formada apenas de 0:

* **eye**: Matriz identidade: matriz quadrada em que todos os elementos da diagonal principal são iguais a 1 e os demais são nulos.

* **rand**: Matrizes com elementos aleatórios uniformemente distribuídos no intervalo [0..1].

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Cria uma matriz (array) nula (preenchida com zeros)
print(a)              # Imprime "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Cria uma matriz (array) com 1 em todas as posições
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Cria uma matriz (array) constante
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Cria uma matriz identidade 2x2
print(d)              # Imprime "[[ 1.  0.]
                      #           [ 0.  1.]]"

e = np.random.random((2,2))  # Cria uma matriz (array) com valores aleatórios
print(e)                     # Pode imprimir "[ [0.9512401  0.3829466 ]
                             #                  [0.76798755 0.79163796] ]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.9512401  0.3829466 ]
 [0.76798755 0.79163796]]


Função numpy.diag (v, k = 0)
----------------------------

Cria uma matriz, colocando os elementos do vetor vetor em uma diagonal paralela à diagonal principal. 

Esta paralela é determinada pelo parâmetro pos, que quando ausente é assumido como 0.

In [ ]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.diag(x)

array([0, 4, 8])

In [ ]:
np.diag(x, k=1)

array([1, 5])

In [ ]:
np.diag(x, k=-1)

array([3, 7])

In [ ]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [ ]:
d = np.pi
d

3.141592653589793

Indexação de matrizes
---------------------

O Numpy oferece várias maneiras de indexar em matrizes.

Slice (fatiar): Semelhante às listas Python, matrizes numpy podem ser fatiadas. 

Como as matrizes podem ser multidimensionais, você deve especificar uma fatia para cada dimensão da matriz:

In [ ]:
import numpy as np

# Crie uma matriz (array) de posto 2 com a forma (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use o fatiamento (slice) para retirar uma sub-matriz com as duas primeira linhas
# e colunas 1 e 2; b é a matriz de forma (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# Uma fatia de uma matriz é uma visão de dentro dos mesmos dados
# logo, caso modificar qualquer dado dessa visão vai impactar na matriz original.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


Você também pode misturar a indexação inteira com a indexação de fatia. No entanto, isso resultará em uma matriz de classificação mais baixa que a matriz original:

In [ ]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

Boolean array indexing: A indexação de matriz booleana permite selecionar elementos arbitrários de uma matriz. Freqüentemente esse tipo de indexação é usado para selecionar os elementos de uma matriz que atendem a alguma condição. Aqui está um exemplo

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


Por uma questão de brevidade, deixamos de fora muitos detalhes sobre a indexação numpy de array; se você quiser saber mais, leia a documentação.

Datatypes
---------

Toda matriz numpy é uma grade de elementos do mesmo tipo. O Numpy fornece um grande conjunto de tipos de dados numéricos que você pode usar para construir matrizes. O Numpy tenta adivinhar um tipo de dados quando você cria uma matriz, mas as funções que constroem matrizes geralmente também incluem um argumento opcional para especificar explicitamente o tipo de dados. Aqui está um exemplo:

In [ ]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

Matemática de matriz
--------------------

As funções matemáticas básicas operam elementares em matrizes e estão disponíveis como sobrecargas do operador e como funções no módulo numpy:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

a = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print('-------')
print(x * y)
print(np.multiply(x, y))
print('-------')
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
-------
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
-------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
import numpy as np

a = np.array([ [1, 3], [4, 5, 6], [7, 8, 9] ])

print(a)

b = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

print(b)


[list([1, 3]) list([4, 5, 6]) list([7, 8, 9])]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Observe que, * é multiplicação por elementos, não multiplicação por matriz. Em vez disso, usamos a função **dot** para calcular produtos internos de vetores, multiplicar um vetor por uma matriz e multiplicar matrizes. **dot** está disponível como uma função no módulo numpy e como um método de instância de objetos de matriz:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Produto interno de vetores; ambos produzem 219
print(v.dot(w))
print(np.dot(v, w))

# Matriz / vetor produto; ambos produzem uma matriz de classificação (posto) 1 [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matriz / matriz produto; ambos produzem uma matriz de classificação (posto) 2
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


O Numpy fornece muitas funções úteis para executar cálculos em matrizes; uma das mais úteis é a **sum**:

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Calcula a soma de todos os elementos; imprime "10"
print(np.sum(x, axis=0))  # Calcula a soma de cada coluna; imprime "[4 6]"
print(np.sum(x, axis=1))  # Calcula a soma de cada linha; imprime "[3 7]"

Você pode encontrar a lista completa de funções matemáticas fornecidas por numpy na documentação.

Além de computar funções matemáticas usando matrizes, frequentemente precisamos remodelar ou manipular dados em matrizes. O exemplo mais simples desse tipo de operação é a transposição de uma matriz; para transpor uma matriz, basta usar o atributo **T** de um objeto de matriz:

In [ ]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

Broadcasting
------------

Broadcasting é um mecanismo poderoso que permite que o numpy trabalhe com matrizes de diferentes formas ao executar operações aritméticas. Freqüentemente, temos uma matriz menor e uma matriz maior, e queremos usar a matriz menor várias vezes para executar alguma operação na matriz maior.

Por exemplo, suponha que desejemos adicionar um vetor constante a cada linha de uma matriz. Poderíamos fazer assim:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

Isso funciona; no entanto, quando a matriz x é muito grande, a computação de um loop explícito no Python pode ser lenta. Observe que adicionar o vetor v a cada linha da matriz x é equivalente a formar uma matriz vv empilhando várias cópias de v verticalmente e, em seguida, executando a soma dos elementos de x e vv. Poderíamos implementar essa abordagem da seguinte maneira:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

Broadcasting numpy nos permite executar esse cálculo sem criar várias cópias do v. Considere esta versão usando broadcasting.

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

A linha y = x + v funciona mesmo que x tenha forma (4, 3) ev tenha forma (3,) devido ao broadcasting; essa linha funciona como se v tivesse realmente a forma (4, 3), em que cada linha era uma cópia de v, e a soma era executada elemento a elemento.

O Broadcasting de duas matrizes juntas segue estas regras:

1. Se as matrizes não tiverem a mesma classificação, acrescente 1s à forma da matriz de classificação inferior, até que as duas formas tenham o mesmo comprimento.
1. As duas matrizes são consideradas compatíveis em uma dimensão se tiverem o mesmo tamanho na dimensão ou se uma das matrizes tiver o tamanho 1 nessa dimensão.
1. As matrizes podem ser transmitidas juntas se forem compatíveis em todas as dimensões.
1. Após a realização do broadcasting, cada matriz se comporta como se tivesse uma forma igual ao máximo de formas elementares das duas matrizes de entrada.
1. Em qualquer dimensão em que uma matriz tenha tamanho 1 e a outra tenha tamanho maior que 1, a primeira matriz se comporta como se tivesse sido copiada ao longo dessa dimensão

Funções que suportam broadcasting são conhecidas como funções universais.

Aqui estão algumas aplicações de broadcasting: 

In [ ]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]

v = np.array([1,2,3])  # v has shape (3,)
x = np.array([[1,2,3], [4,5,6]])

print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

In [ ]:
import numpy as np

v = np.array([1,2,3])  # v has shape (3,)
x = np.array([[1,2,3], [4,5,6]])
a = np.array([[2,3],[4,5]])

# print((x.T + w).T)

print(a)
print(a.T)


# print(a.T + a)

[[2 3]
 [4 5]]
[[2 4]
 [3 5]]
[[13 23]
 [23 41]]
